// <auto-generated />
using System;
using AtosCartorio.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AtosCartorio.Migrations
{
    [DbContext(typeof(CartorioContext))]
    [Migration("20250410212429_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("AtosCartorio.Data.Casamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataCasamento")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataRegistro")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Casamentos");
                });

            modelBuilder.Entity("AtosCartorio.Data.Nascimento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CpfMae")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CpfPai")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataNascimentoMae")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataNascimentoPai")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataRegistro")
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeMae")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NomePai")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeRegistrado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Nascimentos");
                });

            modelBuilder.Entity("AtosCartorio.Data.Obito", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataNascimentoMae")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataNascimentoPai")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataObito")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataRegistro")
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeFalecido")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeMae")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NomePai")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Obitos");
                });

            modelBuilder.Entity("AtosCartorio.Data.Casamento", b =>
                {
                    b.OwnsOne("AtosCartorio.Data.Conjuge", "Conjuge1", b1 =>
                        {
                            b1.Property<int>("CasamentoId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Cpf")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("CpfMae")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("CpfPai")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<DateTime>("DataNascimento")
                                .HasColumnType("TEXT");

                            b1.Property<DateTime?>("DataNascimentoMae")
                                .HasColumnType("TEXT");

                            b1.Property<DateTime?>("DataNascimentoPai")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Nome")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("NomeMae")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("NomePai")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("CasamentoId");

                            b1.ToTable("Casamentos");

                            b1.WithOwner()
                                .HasForeignKey("CasamentoId");
                        });

                    b.OwnsOne("AtosCartorio.Data.Conjuge", "Conjuge2", b1 =>
                        {
                            b1.Property<int>("CasamentoId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Cpf")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("CpfMae")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("CpfPai")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<DateTime>("DataNascimento")
                                .HasColumnType("TEXT");

                            b1.Property<DateTime?>("DataNascimentoMae")
                                .HasColumnType("TEXT");

                            b1.Property<DateTime?>("DataNascimentoPai")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Nome")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("NomeMae")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("NomePai")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("CasamentoId");

                            b1.ToTable("Casamentos");

                            b1.WithOwner()
                                .HasForeignKey("CasamentoId");
                        });

                    b.Navigation("Conjuge1")
                        .IsRequired();

                    b.Navigation("Conjuge2")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
