// <auto-generated />
using System;
using AtosCartorio.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AtosCartorio.Migrations
{
    [DbContext(typeof(CartorioContext))]
    partial class CartorioContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("AtosCartorio.Models.CasamentoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataCasamento")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataRegistro")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Casamentos");
                });

            modelBuilder.Entity("AtosCartorio.Models.NascimentoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CpfMae")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CpfPai")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataNascimentoMae")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataNascimentoPai")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataRegistro")
                        .HasColumnType("TEXT");

                    b.Property<string>("LocalNascimento")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeMae")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NomePai")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Nascimentos");
                });

            modelBuilder.Entity("AtosCartorio.Models.ObitoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataFalecimento")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataNascimentoMae")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataNascimentoPai")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataRegistro")
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeFalecido")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeMae")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NomePai")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Obitos");
                });

            modelBuilder.Entity("AtosCartorio.Models.CasamentoModel", b =>
                {
                    b.OwnsOne("AtosCartorio.Models.ConjugeModel", "Conjuge1", b1 =>
                        {
                            b1.Property<int>("CasamentoModelId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Cpf")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("CpfMae")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("CpfPai")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<DateTime>("DataNascimento")
                                .HasColumnType("TEXT");

                            b1.Property<DateTime?>("DataNascimentoMae")
                                .HasColumnType("TEXT");

                            b1.Property<DateTime?>("DataNascimentoPai")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Nome")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("NomeMae")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("NomePai")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("CasamentoModelId");

                            b1.ToTable("Casamentos");

                            b1.WithOwner()
                                .HasForeignKey("CasamentoModelId");
                        });

                    b.OwnsOne("AtosCartorio.Models.ConjugeModel", "Conjuge2", b1 =>
                        {
                            b1.Property<int>("CasamentoModelId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Cpf")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("CpfMae")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("CpfPai")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<DateTime>("DataNascimento")
                                .HasColumnType("TEXT");

                            b1.Property<DateTime?>("DataNascimentoMae")
                                .HasColumnType("TEXT");

                            b1.Property<DateTime?>("DataNascimentoPai")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Nome")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("NomeMae")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("NomePai")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("CasamentoModelId");

                            b1.ToTable("Casamentos");

                            b1.WithOwner()
                                .HasForeignKey("CasamentoModelId");
                        });

                    b.Navigation("Conjuge1")
                        .IsRequired();

                    b.Navigation("Conjuge2")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
